// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Config struct {
	Key   string
	Value string
}

type Reading struct {
	ID         int64
	ReadAt     time.Time
	ValueM3    float64
	PricePerM3 float64
	Notes      string
}
