// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteReading = `-- name: DeleteReading :exec
DELETE FROM readings WHERE id = ?
`

func (q *Queries) DeleteReading(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReading, id)
	return err
}

const getConfigValue = `-- name: GetConfigValue :one
SELECT value FROM config WHERE key = ?
`

func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getReading = `-- name: GetReading :one
SELECT id, read_at, value_m3, price_per_m3, notes
FROM readings
WHERE id = ?
`

func (q *Queries) GetReading(ctx context.Context, id int64) (Reading, error) {
	row := q.db.QueryRowContext(ctx, getReading, id)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.ReadAt,
		&i.ValueM3,
		&i.PricePerM3,
		&i.Notes,
	)
	return i, err
}

const insertReading = `-- name: InsertReading :one
INSERT INTO readings (read_at, value_m3, price_per_m3, notes)
VALUES (?, ?, ?, ?)
RETURNING id, read_at, value_m3, price_per_m3, notes
`

type InsertReadingParams struct {
	ReadAt     time.Time
	ValueM3    float64
	PricePerM3 float64
	Notes      string
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) (Reading, error) {
	row := q.db.QueryRowContext(ctx, insertReading,
		arg.ReadAt,
		arg.ValueM3,
		arg.PricePerM3,
		arg.Notes,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.ReadAt,
		&i.ValueM3,
		&i.PricePerM3,
		&i.Notes,
	)
	return i, err
}

const listReadings = `-- name: ListReadings :many
SELECT id, read_at, value_m3, price_per_m3, notes
FROM readings
ORDER BY read_at DESC
`

func (q *Queries) ListReadings(ctx context.Context) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.ReadAt,
			&i.ValueM3,
			&i.PricePerM3,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO config (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigValueParams struct {
	Key   string
	Value string
}

func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, setConfigValue, arg.Key, arg.Value)
	return err
}
